### ISSUE TITLE
update build rst script

### ISSUE THREAD

**Issue by alvizek** [SRJPE/SRJPEdata#43]
Move over some of the processing from juvenile_abundance.R in SRJPEmodel to SRJPEdata resulting in one table for catch and one table for mark recapture.

**Comment by ErinCain** [comment]
Selected and filtered table to have one with all catch values and catch related data `weekly_juvenile_abundance_model_catch_data` and one for distinct efficiency trial weeks`weekly_juvenile_abundance_model_efficiency_data`. 

I added an issue in SRJPEmodel to update BTSPAS-X function to take in these 2 tables instead of the one. https://github.com/SRJPE/SRJPEmodel/issues/13
